openapi: "3.0.3"
info:
  title: 社内図書システム
  version: "1.0"
  description: "社内図書システムのAPIドキュメント"
  contact:
    email: dummy@sample.com
    name: dummy
    url: dummy
servers:
  - url: http://localhost:8080
paths:
  /books:
    get:
      description: "本一覧を取得するエンドポイント"
      operationId: books
      tags:
        - "books"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Book"

components:
  schemas:
    $ref: "./components/index.yml"

  examples:
    UserExample:
      value:
        id: 1
        name: aaa
