openapi: "3.0.3"
info:
  title: 社内図書システム
  version: "1.0"
  description: "社内図書システムのAPIドキュメント"
  contact:
    email: dummy@sample.com
    name: dummy
    url: dummy
servers:
  - url: http://localhost:8080
paths:
  /books:
    $ref: "./paths/get-books.yml"
components:
  schemas:
    $ref: "./components/index.yml"
